# Generated by Django 4.2.7 on 2023-12-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyTransfer',
        ),
    ]
